//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.11 at 09:38:37 PM CEST 
//


package brickBreaker;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for highscoreType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="highscoreType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="player" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bricksRemaining" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="timeMillis" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "highscoreType", propOrder = {
    "player",
    "bricksRemaining",
    "timeMillis"
})
public class HighscoreType {

    @XmlElement(required = true)
    protected String player;
    protected int bricksRemaining;
    protected int timeMillis;

    /**
     * Gets the value of the player property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayer() {
        return player;
    }

    /**
     * Sets the value of the player property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayer(String value) {
        this.player = value;
    }

    /**
     * Gets the value of the bricksRemaining property.
     * 
     */
    public int getBricksRemaining() {
        return bricksRemaining;
    }

    /**
     * Sets the value of the bricksRemaining property.
     * 
     */
    public void setBricksRemaining(int value) {
        this.bricksRemaining = value;
    }

    /**
     * Gets the value of the timeMillis property.
     * 
     */
    public int getTimeMillis() {
        return timeMillis;
    }

    /**
     * Sets the value of the timeMillis property.
     * 
     */
    public void setTimeMillis(int value) {
        this.timeMillis = value;
    }

}
