//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.11 at 09:38:37 PM CEST 
//


package brickBreaker;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HighscoreList_QNAME = new QName("", "highscoreList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HighscoreListType }
     * 
     */
    public HighscoreListType createHighscoreListType() {
        return new HighscoreListType();
    }

    /**
     * Create an instance of {@link HighscoreType }
     * 
     */
    public HighscoreType createHighscoreType() {
        return new HighscoreType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HighscoreListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "highscoreList")
    public JAXBElement<HighscoreListType> createHighscoreList(HighscoreListType value) {
        return new JAXBElement<HighscoreListType>(_HighscoreList_QNAME, HighscoreListType.class, null, value);
    }

}
